### ISSUE TITLE
Update Readme/Documentaion

### ISSUE THREAD

**Issue by Raporaz03** [VaibhavAswal/startYourJourneyHere#3]
I will update your documentation by adding following things

1. Instructions for beginners.
2. Adding attractive images and gifs 
3. Information about project. What to do /things needed

Can I start?

**Comment by VaibhavAswal** [comment]
Sure @Raporaz03 , go ahead! :)

**Comment by Raporaz03** [comment]
Every one leave this issue. I had started the work.

**Comment by Raporaz03** [comment]
updated
